# Generated by Django 3.0.5 on 2020-04-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default='Article Description', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='https://unsplash.it/400/400', upload_to=''),
            preserve_default=False,
        ),
    ]
